identifier: notification-service
title: Notification Service
blueprint: Microservice
properties:
  slackChannel: "https://yourslack.slack.com/archives/CHANNEL-ID"
  repoUrl: "https://github.com/port-labs/resource-catalog-microservice-repo"
